import {buildWorld} from './world.js';
import {VoxelRenderer} from './renderer.js';
const stage=document.querySelector('#stage'),canvas=document.querySelector('#world'),rainCanvas=document.querySelector('#rain'),rainCtx=rainCanvas.getContext('2d');
const live=document.querySelector('#live'),card=document.querySelector('#place-card'),markers=[...document.querySelectorAll('[data-place]')];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const world=buildWorld();let renderer;
try{renderer=new VoxelRenderer(canvas,world)}catch(error){document.querySelector('#fallback').hidden=false;console.error(error)}
const starting={yaw:.65,pitch:.51,radius:window.innerWidth<760?112:70,target:[-6,9,0]};
const camera={...starting,target:[...starting.target]},desired={...starting,target:[...starting.target]};
const places={house:{title:'Orman evi',index:'01 / ORMAN EVİ',text:'Taş bir kaidenin üzerine oturan evin ahşap terası, kıyıya inen patikaya bakıyor. İçerideki sıcak ışık geceleri ormanın küçük fenerine dönüşür.',target:[-9,16,-2],yaw:.55,pitch:.39,radius:35},waterfall:{title:'Taşların arasından',index:'02 / ŞELALE',text:'Su yüksek çayırdan kopup düzensiz basamaklarla kıyıya iner. Aynı akışın iki anı birbirine benzemez.',target:[20,7,8],yaw:1,pitch:.48,radius:40},forest:{title:'Yaban ormanı',index:'03 / ORMAN',text:'Çamlar, geniş yapraklı ağaçlar, kayalar ve yabani çiçekler rastlantıyla yer bulur. Patika vardır, ama orman onun düzenine uymaz.',target:[-27,11,14],yaw:-.5,pitch:.55,radius:43}};
let selected=null,wantedTime=0,currentTime=0,raining=false,lights=true,elapsed=0,lastFrame=0,dragged=false;
const pointerMap=new Map();let lastPinch=0;
function focus(place,closer=false){const p=places[place];if(!p)return;desired.target=[...p.target];desired.yaw=p.yaw;desired.pitch=p.pitch;desired.radius=p.radius*(closer?.65:1);selected=place;card.hidden=false;document.querySelector('#card-index').textContent=p.index;document.querySelector('#card-title').textContent=p.title;document.querySelector('#card-text').textContent=p.text;live.textContent=p.title+' keşfedildi';markers.forEach(b=>b.classList.toggle('selected',b.dataset.place===place))}
function reset(){desired.target=[...starting.target];desired.yaw=starting.yaw;desired.pitch=starting.pitch;desired.radius=starting.radius;card.hidden=true;selected=null;markers.forEach(b=>b.classList.remove('selected'));live.textContent='Genel görünüme dönüldü'}
markers.forEach(b=>b.addEventListener('click',()=>focus(b.dataset.place)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>focus(b.dataset.go)));
document.querySelector('#explore').addEventListener('click',()=>focus('house',true));
document.querySelector('#focus-card').addEventListener('click',()=>{if(selected)focus(selected,true)});
document.querySelector('#close-card').addEventListener('click',()=>{card.hidden=true;selected=null;markers.forEach(b=>b.classList.remove('selected'))});
document.querySelector('#reset-view').addEventListener('click',reset);
document.querySelector('#zoom-in').addEventListener('click',()=>desired.radius=clamp(desired.radius*.78,23,155));
document.querySelector('#zoom-out').addEventListener('click',()=>desired.radius=clamp(desired.radius*1.28,23,155));
const buttons=[...document.querySelectorAll('[data-time]')];buttons.forEach(b=>b.addEventListener('click',()=>{wantedTime=+b.dataset.time;buttons.forEach(x=>{let on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});const name=wantedTime===0?'GÜNDÜZ':wantedTime===.5?'GÜN BATIMI':'GECE';document.querySelector('#time-label').textContent=name;live.textContent=name+' ışığına geçiliyor'}));
document.querySelector('#rain-toggle').addEventListener('click',e=>{raining=!raining;e.currentTarget.classList.toggle('active',raining);e.currentTarget.setAttribute('aria-pressed',raining);live.textContent=raining?'Yağmur başladı':'Yağmur dindi'});
document.querySelector('#light-toggle').addEventListener('click',e=>{lights=!lights;e.currentTarget.classList.toggle('active',lights);e.currentTarget.setAttribute('aria-pressed',lights);live.textContent=lights?'Ev ışıkları açık':'Ev ışıkları kapalı'});
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointerMap.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY});dragged=false;if(pointerMap.size===2){const [a,b]=[...pointerMap.values()];lastPinch=Math.hypot(a.x-b.x,a.y-b.y)}});
canvas.addEventListener('pointermove',e=>{const p=pointerMap.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;if(Math.abs(p.x-p.startX)+Math.abs(p.y-p.startY)>6)dragged=true;
 if(pointerMap.size===2){const [a,b]=[...pointerMap.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(lastPinch>0)desired.radius=clamp(desired.radius*lastPinch/Math.max(1,distance),23,155);lastPinch=distance;return}
 desired.yaw-=dx*.006;desired.pitch=clamp(desired.pitch+dy*.005,.16,1.34)});
canvas.addEventListener('pointerup',e=>{if(!dragged&&pointerMap.size===1&&renderer){let nearest=null,d=55;for(const [name,point] of Object.entries(world.features)){const p=renderer.point(point);if(p?.visible){const r=canvas.getBoundingClientRect(),dist=Math.hypot(e.clientX-r.left-p.x,e.clientY-r.top-p.y);if(dist<d){d=dist;nearest=name}}}if(nearest)focus(nearest)}pointerMap.delete(e.pointerId);lastPinch=0});
canvas.addEventListener('pointercancel',e=>{pointerMap.delete(e.pointerId);lastPinch=0});
canvas.addEventListener('wheel',e=>{e.preventDefault();desired.radius=clamp(desired.radius*Math.exp(e.deltaY*.0011),23,155)},{passive:false});
canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')desired.yaw-=.12;else if(e.key==='ArrowRight')desired.yaw+=.12;else if(e.key==='ArrowUp')desired.pitch=clamp(desired.pitch-.1,.16,1.34);else if(e.key==='ArrowDown')desired.pitch=clamp(desired.pitch+.1,.16,1.34);else if(e.key==='+'||e.key==='=')desired.radius=clamp(desired.radius*.84,23,155);else if(e.key==='-')desired.radius=clamp(desired.radius*1.2,23,155);else return;e.preventDefault()});
const drops=Array.from({length:115},()=>({x:Math.random(),y:Math.random(),speed:.56+Math.random()*.8,len:9+Math.random()*17}));
function drawRain(dt){const w=stage.clientWidth,h=stage.clientHeight,ratio=Math.min(devicePixelRatio||1,1.35),rw=Math.floor(w*ratio),rh=Math.floor(h*ratio);if(rainCanvas.width!==rw||rainCanvas.height!==rh){rainCanvas.width=rw;rainCanvas.height=rh}rainCtx.setTransform(ratio,0,0,ratio,0,0);rainCtx.clearRect(0,0,w,h);if(!raining)return;rainCtx.strokeStyle=currentTime>.8?'#d0dcef71':'#e8f5ed82';rainCtx.lineWidth=1;rainCtx.beginPath();for(const d of drops){d.y+=dt*d.speed;d.x-=dt*.08;if(d.y>1.1){d.y=-.08;d.x=Math.random()}if(d.x<0)d.x=1;let x=d.x*w,y=d.y*h;rainCtx.moveTo(x,y);rainCtx.lineTo(x-4,y+d.len)}rainCtx.stroke()}
function animate(timestamp){requestAnimationFrame(animate);if(!renderer||document.hidden)return;if(timestamp-lastFrame<20)return;const dt=lastFrame?Math.min((timestamp-lastFrame)/1000,.08):.02;lastFrame=timestamp;elapsed+=dt;const ease=1-Math.exp(-dt*4.8);for(const k of ['yaw','pitch','radius'])camera[k]+=(desired[k]-camera[k])*ease;for(let i=0;i<3;i++)camera.target[i]+=(desired.target[i]-camera.target[i])*ease;currentTime+=(wantedTime-currentTime)*(1-Math.exp(-dt*1.65));
 let t=renderer.draw(camera,currentTime,raining,elapsed,lights);stage.style.setProperty('--skyTop',t.top);stage.style.setProperty('--skyBottom',t.bottom);stage.style.setProperty('--sun',t.sunCss);stage.style.setProperty('--night',t.night);stage.style.setProperty('--sunOpacity',1-t.night*.66);
 for(const b of markers){const p=renderer.point(world.features[b.dataset.place]);b.hidden=!p?.visible;if(!b.hidden){b.style.left=p.x+'px';b.style.top=p.y+'px'}}drawRain(dt)}
requestAnimationFrame(animate);
